### ISSUE TITLE
Invalid rotation in euclid causes panic in Cycle

### ISSUE THREAD

**Issue by emuell** [emuell/afseq#10]
Example:

```
cycle("e4(1,1,2)")
```

Any rotation value > pulse count will cause this.

https://github.com/emuell/afseq/blob/2512ae2b131e42ee2f246c734e2a51466e5fc056/src/tidal/cycle.rs#L724

**Comment by unlessgames** [comment]
Odd, I thought rotate_left was safer than this.

**Comment by unlessgames** [comment]
Think I should've read the docs properly here. Is there something clippy or the lsp can do to warn about such possible panics?
