### ISSUE TITLE
Parsing nested groups

### ISSUE THREAD

**Issue by unlessgames** [emuell/afseq#23]
As mentioned on the forum, parsing expressions like `[ [ [ [ ] ] ] ]` takes a long time for pest with the current rules.

I found [this issue](https://github.com/pest-parser/pest/issues/458) on the pest github that seems relevant. 

Clearly the rules inside `group`s have some similar retrying that was mentioned on the issue as for example a `stack` can have a `split` or a `section` inside while a `group` can have a `stack`, `split` or `section` but I'm not sure how we could optimize this exactly and profiling might be a good idea before trying to do anything here.

**Comment by emuell** [comment]
This seems to be s general Pest issue after all. 

See also https://github.com/martinohmann/hcl-rs/issues/82

Let me know if I can help setting up some benchmarks or writing a guide on how to profile this. I can try taking care of this issue too next week if you don't have time for that.
